[workspace]
resolver = "2"

members = ["crates/*"]

[workspace.dependencies]
insta = "1.41.1"
oxc_allocator = "0.42.0"
oxc_ast = "0.42.0"
oxc_codegen = "0.42.0"
oxc_index = "2.0.0"
oxc_parser = "0.42.0"
oxc_semantic = "0.42.0"
